### ISSUE TITLE
Feature TODO List

### ISSUE THREAD

**Issue by anuragmakineni** [raphaelchang/battman-firmware#1]
- [ ] Turn Board On
- [ ] Turn Board Off
- [ ] SPI Support (ADC and Balancer)
- [ ] Detect Charger Plugged In
- [ ] Charging Algorithm  
  1. Enable Charging Circuit
  2. Balance Cells
  3. Disable Charging Circuit 
- [ ] Current Sensor Read
- [ ] Coulomb Counting
- [ ] Over Current Protection
- [ ] Under Voltage Protection
- [ ] Over Voltage Protection
- [ ] CAN Support
